<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Main multirotor link -->
    <xacro:macro name="multirotor_base_macro"
    params="robot_namespace mass body_width body_height mesh_file mesh_scale color *inertia">

    <link name="base_link"></link>

    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_link_inertia" />
    </joint>

    <link name="base_link_inertia">
        <inertial>
        <mass value="${mass}" />  <!-- [kg] -->
        <origin xyz="0 0 0" />
        <xacro:insert_block name="inertia" />
        </inertial>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="${mesh_file}" scale="${mesh_scale}" />
            <!-- <box size="${body_width} ${body_width} ${body_height}"/> --> <!-- [m] [m] [m] -->
        </geometry>
        </visual>

        <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <!-- [m] [m] [m] -->
            <box size="${body_width} ${body_width} ${body_height}" /> 
        </geometry>
        </collision>
    </link>

    <!-- attach multirotor_base_plugin to the base_link -->
    <gazebo>
        <plugin filename="librotors_gazebo_multirotor_base_plugin.so" name="multirotor_base_plugin">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <linkName>base_link</linkName>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="BuoyancyPlugin" filename="libbuoyancy_gazebo_plugin.so">
        <fluid_density>997</fluid_density>
        <linear_drag>100</linear_drag>
        <angular_drag>20</angular_drag>

        <buoyancy name="buoyancy_base">
            <link_name>base_link</link_name>
            <pose>0 0 -0.03 0 0 0</pose>
            <geometry>
                <box>
                    <size>0.4 0.4 0.2</size>
                </box>
            </geometry>
        </buoyancy>
        <link name="body">
        <volume>100</volume>
        </link>
        </plugin>
    </gazebo>

    <gazebo reference="base_link">
        <material>Gazebo/${color}</material>
    </gazebo>
    </xacro:macro>

    <!-- Rotor joint and link -->
    <xacro:macro name="vertical_rotor"
    params="robot_namespace suffix direction motor_constant moment_constant parent mass_rotor radius_rotor time_constant_up time_constant_down max_rot_velocity motor_number rotor_drag_coefficient rolling_moment_coefficient color mesh mesh_scale *origin *inertia">
    <joint name="rotor_${motor_number}_joint" type="continuous">
        <xacro:insert_block name="origin" />
        <axis xyz="0 0 1" />
        <!-- TODO(ff): not currently set because it's not yet supported -->
        <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
        <parent link="${parent}" />
        <child link="rotor_${motor_number}" />

    </joint>

    <!-- TODO(ff): not currently set because it's not yet supported -->
    <!-- <gazebo reference="rotor_${motor_number}_joint"> <axis> <xyz>0 0 1</xyz>
        <limit> <velocity> ${max_rot_velocity} </velocity> </limit> </axis> </gazebo> -->
    <link name="rotor_${motor_number}">
        <inertial>
        <mass value="${mass_rotor}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
        </inertial>
        <visual>
        <geometry>
            <!-- <cylinder length="0.005" radius="${radius_rotor}"/> --> <!-- [m] -->
            <!-- <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae" -->
            <mesh filename="package://dji_m210_description/meshes/propeller_${direction}.dae"
            scale="${mesh_scale}" />
            <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
        </geometry>
        </visual>
        <collision>
        <geometry>
            <cylinder length="0.005" radius="${radius_rotor}" /> <!-- [m] -->
        </geometry>
        </collision>
    </link>
    <gazebo>
        <plugin name="${robot_namespace}_${suffix}_motor_model" filename="librotors_gazebo_motor_model.so">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <jointName>rotor_${motor_number}_joint</jointName>
        <linkName>rotor_${motor_number}</linkName>
        <turningDirection>${direction}</turningDirection>
        <timeConstantUp>${time_constant_up}</timeConstantUp>
        <timeConstantDown>${time_constant_down}</timeConstantDown>
        <maxRotVelocity>${max_rot_velocity}</maxRotVelocity>
        <motorConstant>${motor_constant}</motorConstant>
        <momentConstant>${moment_constant}</momentConstant>
        <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
        <motorNumber>${motor_number}</motorNumber>
        <rotorDragCoefficient>${rotor_drag_coefficient}</rotorDragCoefficient>
        <rollingMomentCoefficient>${rolling_moment_coefficient}</rollingMomentCoefficient>
        <motorSpeedPubTopic>motor_speed/${motor_number}</motorSpeedPubTopic>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
        </plugin>
    </gazebo>
    <gazebo reference="rotor_${motor_number}">
        <material>Gazebo/${color}</material>
    </gazebo>
    </xacro:macro>
</robot>